export const FETCH_SHORT_LINKS = 'FETCH_SHORT_LINKS';
export const FETCH_SHORT_LINK = 'FETCH_SHORT_LINK';

export const FETCHING_SHORT_LINKS = 'FETCHING_SHORT_LINKS';
export const FETCHING_SHORT_LINK = 'FETCHING_SHORT_LINK';